name:                Maze
version:             0.1.0.0
github:              "neco8/Maze"
license:             BSD3
author:              "neco8"
maintainer:          "shogibeshow@gmail.com"
copyright:           "2021 neco8"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/neco8/Maze#readme>

dependencies:
- base >= 4.7 && < 5
- ilist
- random
- monad-loops

library:
  source-dirs: src

executables:
  Maze-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Maze

tests:
  Maze-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Maze
